[package]
name = "rustee-storage"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Encrypted ree-fs. Not GP trusted storage. Not anti-rollback."

[dependencies]
rustee-hal = { workspace = true }
rustee-crypto = { workspace = true }
rustee-proto = { workspace = true }
